[theme]
base = "light"
primaryColor = "#EF674E"
backgroundColor = "#F5F1E9"
secondaryBackgroundColor = "#FFFDF8"
textColor = "#171717"
font = "sans serif"

[server]
headless = true
runOnSave = true
maxUploadSize = 16

[browser]
gatherUsageStats = false